export type Product = {
  slug: string;
  name: string;
  category: "disposables" | "devices" | "accessories";
  categoryLabel: string;
  price: number;
  salePrice?: number;
  image: string;
  images?: string[];
  flavour?: string;
  puffs?: string;
  battery?: string;
  capacity?: string;
  nicotine?: string;
  colors?: { name: string; hex: string }[];
  description: string;
  bestseller?: boolean;
};

export const products: Product[] = [
  {
    slug: "iget-shion-lychee-ice-600-puffs",
    name: "IGET Shion Lychee Ice",
    category: "disposables",
    categoryLabel: "IGET Shion 600",
    price: 9.95,
    image: "/products/iget-shion-lychee-ice-600-puffs.png",
    flavour: "Lychee Ice",
    puffs: "600",
    battery: "400MAH",
    capacity: "2.4ML",
    nicotine: "20 mg/mL",
    description: "IGET SHION LYCHEE ICE Disposable Pods Stick is a top quality vape by IGET. It is powered by a 400 MAH Battery and it holds 2.4 ML of e-liquid. IGET are pre-infused with a variety of salt nicotine flavours. The device is super sleek,…",
    bestseller: true,
  },
  {
    slug: "jnr-cruiser-passion-fruit-mango-lime-12000-puffs",
    name: "JNR Cruiser Passion Fruit Mango Lime",
    category: "disposables",
    categoryLabel: "JNR Cruiser 12000 Puffs",
    price: 84.95,
    salePrice: 69.95,
    image: "/products/jnr-cruiser-passion-fruit-mango-lime-12000-puffs.webp",
    flavour: "Passion Fruit Mango Lime",
    puffs: "12000",
    battery: "3500mAh",
    capacity: "25ml",
    nicotine: "20 mg/mL",
    description: "Experience a tropical fusion with the JNR Cruiser Passion Fruit Mango Lime 12000 Puffs . This vibrant blend combines the exotic sweetness of ripe passion fruit, the juicy richness of mango, and a zesty splash of lime for a refreshing…",
  },
  {
    slug: "double-happiness-hype-flat-white-12000-puffs",
    name: "Double Happiness Hype Flat White",
    category: "disposables",
    categoryLabel: "Double Happiness Hype 12000 Puffs",
    price: 69.95,
    image: "/products/double-happiness-hype-flat-white-12000-puffs.png",
    flavour: "Flat White",
    puffs: "12000",
    battery: "550mAh",
    capacity: "18mL",
    nicotine: "50 mg/mL",
    description: "Enjoy the smooth, creamy taste of café-style coffee with DOUBLE HAPPINESS HYPE FLAT WHITE – 12,000 PUFFS . Inspired by the classic flat white, this premium disposable vape blends rich espresso notes with velvety milk for a warm and…",
  },
  {
    slug: "double-happiness-hype-greek-yogurt-12000-puffs",
    name: "Double Happiness Hype Greek Yogurt",
    category: "disposables",
    categoryLabel: "Double Happiness Hype 12000 Puffs",
    price: 69.95,
    image: "/products/double-happiness-hype-greek-yogurt-12000-puffs.png",
    flavour: "Greek Yogurt",
    puffs: "12000",
    battery: "550mAh",
    capacity: "18mL",
    nicotine: "50 mg/mL",
    description: "Indulge in the rich, creamy taste of DOUBLE HAPPINESS HYPE GREEK YOGURT – 12,000 PUFFS . This unique disposable vape delivers the smooth flavour of authentic Greek yogurt with a subtle sweet and tangy finish, offering a refreshingly…",
  },
  {
    slug: "double-happiness-hype-strawberry-raspberry-12000-puffs",
    name: "Double Happiness Hype Strawberry Raspberry",
    category: "disposables",
    categoryLabel: "Double Happiness Hype 12000 Puffs",
    price: 69.95,
    image: "/products/double-happiness-hype-strawberry-raspberry-12000-puffs.png",
    flavour: "Strawberry Raspberry",
    puffs: "12000",
    battery: "550mAh",
    capacity: "18mL",
    nicotine: "50 mg/mL",
    description: "Enjoy the perfect blend of sweet strawberries and tangy raspberries with DOUBLE HAPPINESS HYPE STRAWBERRY RASPBERRY – 12,000 PUFFS . This premium disposable vape delivers a smooth, fruity flavour profile with a refreshing finish, making it…",
  },
  {
    slug: "double-happiness-hype-strawberry-watermelon-12000-puffs",
    name: "Double Happiness Hype Strawberry Watermelon",
    category: "disposables",
    categoryLabel: "Double Happiness Hype 12000 Puffs",
    price: 69.95,
    image: "/products/double-happiness-hype-strawberry-watermelon-12000-puffs.png",
    flavour: "Strawberry Watermelon",
    puffs: "12000",
    battery: "550mAh",
    capacity: "18mL",
    nicotine: "50 mg/mL",
    description: "Enjoy the refreshing combination of sweet strawberries and juicy watermelon with DOUBLE HAPPINESS HYPE STRAWBERRY WATERMELON – 12,000 PUFFS . This premium disposable vape delivers a perfectly balanced fruit blend, offering smooth flavour…",
  },
  {
    slug: "double-happiness-hype-love-66-12000-puffs",
    name: "Double Happiness Hype Love 66",
    category: "disposables",
    categoryLabel: "Double Happiness Hype 12000 Puffs",
    price: 69.95,
    image: "/products/double-happiness-hype-love-66-12000-puffs.png",
    flavour: "Love 66",
    puffs: "12000",
    battery: "550mAh",
    capacity: "18mL",
    nicotine: "50 mg/mL",
    description: "Experience the iconic taste of DOUBLE HAPPINESS HYPE LOVE 66 – 12,000 PUFFS . This premium disposable vape features a unique fusion of sweet tropical fruits, refreshing watermelon, and cool mint, delivering a smooth and flavourful vaping…",
  },
  {
    slug: "double-happiness-hype-double-happiness-12000-puffs",
    name: "Double Happiness Hype Double Happiness",
    category: "disposables",
    categoryLabel: "Double Happiness Hype 12000 Puffs",
    price: 69.95,
    image: "/products/double-happiness-hype-double-happiness-12000-puffs.png",
    flavour: "Double Happiness",
    puffs: "12000",
    battery: "550mAh",
    capacity: "18mL",
    nicotine: "50 mg/mL",
    description: "Experience the signature taste of DOUBLE HAPPINESS HYPE DOUBLE HAPPINESS – 12,000 PUFFS . This unique flavour offers a smooth, well-balanced blend with subtly sweet and refreshing notes, delivering a satisfying vape that's perfect for…",
  },
  {
    slug: "double-happiness-hype-blueberry-raspberry-12000-puffs",
    name: "Double Happiness Hype Blueberry Raspberry",
    category: "disposables",
    categoryLabel: "Double Happiness Hype 12000 Puffs",
    price: 69.95,
    image: "/products/double-happiness-hype-blueberry-raspberry-12000-puffs.jpg",
    flavour: "Blueberry Raspberry",
    puffs: "12000",
    battery: "550mAh",
    capacity: "18mL",
    nicotine: "50 mg/mL",
    description: "Experience a delicious fusion of sweet blueberries and tangy raspberries with the DOUBLE HAPPINESS HYPE BLUEBERRY RASPBERRY – 12,000 PUFFS . This premium disposable vape delivers a perfectly balanced berry blend, offering a smooth and…",
  },
  {
    slug: "double-happiness-hype-12000-puffs-3-pack",
    name: "Double Happiness Hype 12000 Puffs - 3 Pack",
    category: "disposables",
    categoryLabel: "Double Happiness Hype 12000 Puffs",
    price: 206.85,
    image: "/products/double-happiness-hype-12000-puffs-3-pack.jpg",
    flavour: "12000 Puffs - 3 Pack",
    puffs: "12000",
    battery: "550mAh",
    capacity: "18mL",
    nicotine: "50 mg/mL",
    description: "Get more value with the DOUBLE HAPPINESS HYPE 12,000 PUFFS – 3 PACK . Featuring three premium rechargeable disposable vapes, this bundle is perfect for stocking up on your favourite flavours or trying something new. Each device delivers up…",
  },
  {
    slug: "double-happiness-hype-strawberry-lollipop-12000-puffs",
    name: "Double Happiness Hype Strawberry Lollipop",
    category: "disposables",
    categoryLabel: "Double Happiness Hype 12000 Puffs",
    price: 69.95,
    image: "/products/double-happiness-hype-strawberry-lollipop-12000-puffs.jpg",
    flavour: "Strawberry Lollipop",
    puffs: "12000",
    battery: "550mAh",
    capacity: "18mL",
    nicotine: "50 mg/mL",
    description: "Treat yourself to the sweet, candy-inspired taste of DOUBLE HAPPINESS HYPE STRAWBERRY LOLLIPOP – 12,000 PUFFS . Blending the juicy flavour of ripe strawberries with the nostalgic sweetness of a classic lollipop, this premium disposable…",
  },
  {
    slug: "double-happiness-hype-cherry-pomegranate-12000-puffs",
    name: "Double Happiness Hype Cherry Pomegranate",
    category: "disposables",
    categoryLabel: "Double Happiness Hype 12000 Puffs",
    price: 69.95,
    image: "/products/double-happiness-hype-cherry-pomegranate-12000-puffs.jpg",
    flavour: "Cherry Pomegranate",
    puffs: "12000",
    battery: "550mAh",
    capacity: "18mL",
    nicotine: "50 mg/mL",
    description: "Enjoy the bold combination of sweet cherries and rich pomegranate with the DOUBLE HAPPINESS HYPE CHERRY POMEGRANATE – 12,000 PUFFS . This premium disposable vape delivers a smooth, fruity flavour with the perfect balance of sweetness and…",
  },
  {
    slug: "double-happiness-hype-blackberry-12000-puffs",
    name: "Double Happiness Hype Blackberry",
    category: "disposables",
    categoryLabel: "Double Happiness Hype 12000 Puffs",
    price: 69.95,
    image: "/products/double-happiness-hype-blackberry-12000-puffs.jpg",
    flavour: "Blackberry",
    puffs: "12000",
    battery: "550mAh",
    capacity: "18mL",
    nicotine: "50 mg/mL",
    description: "Enjoy the rich, juicy taste of ripe blackberries with the DOUBLE HAPPINESS HYPE BLACKBERRY – 12,000 PUFFS . This premium disposable vape delivers a smooth berry flavour with every puff, combining long-lasting performance with a sleek,…",
  },
  {
    slug: "alibarbar-ingot-ribena-9000-puffs",
    name: "Alibarbar Ingot Ribena",
    category: "disposables",
    categoryLabel: "Alibarbar 9000",
    price: 79.95,
    image: "/products/alibarbar-ingot-ribena-9000-puffs.jpg",
    flavour: "Ingot Ribena",
    puffs: "9000",
    battery: "2350mAh",
    capacity: "22ml",
    nicotine: "20 mg/mL",
    description: "Product Specifications: E-liquid Capacity: 22ml Battery Capacity: 2350mah Puffs: Up to 9000 Size: 103x40x26mm Net Weight: 90g Coil Resistance: 1.2Ω Non-rechargeable LED display",
  },
  {
    slug: "alibarbar-ingot-miami-mint-9000-puffs",
    name: "Alibarbar Ingot Miami Mint",
    category: "disposables",
    categoryLabel: "Alibarbar 9000",
    price: 79.95,
    image: "/products/alibarbar-ingot-miami-mint-9000-puffs.jpg",
    flavour: "Ingot Miami Mint",
    puffs: "9000",
    nicotine: "20 mg/mL",
    description: "🍃 Overview Compact disposable with up to 9000 puffs , bold mint chill.",
  },
  {
    slug: "fisco-xpod-double-apple-8000-puffs",
    name: "Fisco Xpod Double Apple",
    category: "disposables",
    categoryLabel: "Fisco Xpod",
    price: 59.95,
    image: "/products/fisco-xpod-double-apple-8000-puffs.png",
    flavour: "Double Apple",
    puffs: "8000",
    nicotine: "20 mg/mL",
    description: "🍏 Overview The FISCO Xpod DOUBLE APPLE 8000 Puffs delivers a crisp and juicy green-apple shisha-style flavor, blending sweet orchard fruit with subtle hookah-inspired smoothness. Every puff offers a light, flavorful experience with a hint…",
  },
  {
    slug: "fisco-xpod-spearmint-8000-puffs-pod-only",
    name: "Fisco Xpod Spearmint - 8000 Puffs (pod Only)",
    category: "disposables",
    categoryLabel: "Fisco Xpod",
    price: 59.95,
    image: "/products/fisco-xpod-spearmint-8000-puffs-pod-only.png",
    flavour: "Spearmint - 8000 Puffs (pod Only)",
    puffs: "8000",
    nicotine: "20 mg/mL",
    description: "🍏 Overview The FISCO Xpod SPEARMINT 8000 Puffs delivers a crisp and juicy green-apple shisha-style flavor, blending sweet orchard fruit with subtle hookah-inspired smoothness. Every puff offers a light, flavorful experience with a hint of…",
  },
  {
    slug: "calibarn-peach-watermelon-6000-puffs",
    name: "Calibarn Peach Watermelon",
    category: "disposables",
    categoryLabel: "Calibarn 6000",
    price: 39.95,
    image: "/products/calibarn-peach-watermelon-6000-puffs.jpg",
    flavour: "Peach Watermelon",
    puffs: "6000",
    nicotine: "20 mg/mL",
    description: "Compact disposable vape featuring a delicious Peach Watermelon blend with up to 6000 puffs for extended enjoyment.",
  },
  {
    slug: "calibarn-lemon-mint-6000-puffs",
    name: "Calibarn Lemon Mint",
    category: "disposables",
    categoryLabel: "Calibarn 6000",
    price: 39.95,
    image: "/products/calibarn-lemon-mint-6000-puffs.jpg",
    flavour: "Lemon Mint",
    puffs: "6000",
    nicotine: "20 mg/mL",
    description: "Compact disposable vape featuring a refreshing Lemon flavor with up to 6000 puffs for long-lasting enjoyment.",
  },
  {
    slug: "rival-bar-long-jin-tea-8000-puffs-2",
    name: "Rival Bar Long Jin Tea",
    category: "disposables",
    categoryLabel: "Rival Bar 8000",
    price: 49.95,
    image: "/products/rival-bar-long-jin-tea-8000-puffs-2.png",
    flavour: "Long Jin Tea",
    puffs: "8000",
    nicotine: "20 mg/mL",
    description: "🍓 Overview RIVAL BAR LONG JIN TEA is a unique disposable vape offering up to 8000 puffs, crafted for users who enjoy a smooth tea-inspired flavor with a light, refined character.",
  },
  {
    slug: "rival-bar-lime-8000-puffs-2",
    name: "Rival Bar Lime",
    category: "disposables",
    categoryLabel: "Rival Bar 8000",
    price: 49.95,
    image: "/products/rival-bar-lime-8000-puffs-2.jpg",
    flavour: "Lime",
    puffs: "8000",
    nicotine: "20 mg/mL",
    description: "🍓 Overview RIVAL BAR LIME is a lively disposable vape delivering up to 8000 puffs, ideal for users who enjoy a crisp citrus flavor with a refreshing and slightly tangy edge.",
  },
  {
    slug: "rival-bar-cola-8000-puffs-2",
    name: "Rival Bar Cola",
    category: "disposables",
    categoryLabel: "Rival Bar 8000",
    price: 49.95,
    image: "/products/rival-bar-cola-8000-puffs-2.png",
    flavour: "Cola",
    puffs: "8000",
    nicotine: "20 mg/mL",
    description: "🍓 Overview RIVAL BAR COLA is a bold disposable vape delivering up to 8000 puffs, made for users who enjoy the fizzy, sweet taste of classic cola in a smooth all-day format.",
  },
  {
    slug: "rival-bar-grape-8000-puffs",
    name: "Rival Bar Grape",
    category: "disposables",
    categoryLabel: "Rival Bar 8000",
    price: 49.95,
    image: "/products/rival-bar-grape-8000-puffs.jpg",
    flavour: "Grape",
    puffs: "8000",
    nicotine: "20 mg/mL",
    description: "Experience the bold and juicy taste of RIVAL BAR Grape, delivering a rich burst of sweet grape flavor with every puff. Designed for convenience and long-lasting enjoyment, this premium disposable vape provides up to 8000 puffs in a sleek…",
  },
  {
    slug: "jnr-cruiser-strawberry-lychee-12000-puffs",
    name: "JNR Cruiser Strawberry Lychee",
    category: "disposables",
    categoryLabel: "JNR Cruiser 12000 Puffs",
    price: 84.95,
    salePrice: 69.95,
    image: "/products/jnr-cruiser-strawberry-lychee-12000-puffs.jpg",
    flavour: "Strawberry Lychee",
    puffs: "12000",
    nicotine: "20 mg/mL",
    description: "Experience a delightful fusion of fruity sweetness with the JNR Cruiser Strawberry Lychee 12000 Puffs. Combining the juicy taste of ripe strawberries with the exotic sweetness of lychee, this premium disposable vape delivers a smooth,…",
  },
  {
    slug: "jnr-cruiser-banana-buzz-12000-puffs",
    name: "JNR Cruiser Banana Buzz",
    category: "disposables",
    categoryLabel: "JNR Cruiser 12000 Puffs",
    price: 84.95,
    salePrice: 69.95,
    image: "/products/jnr-cruiser-banana-buzz-12000-puffs.jpg",
    flavour: "Banana Buzz",
    puffs: "12000",
    nicotine: "20 mg/mL",
    description: "Treat yourself to the smooth and creamy taste of the JNR Cruiser Banana Buzz 12000 Puffs. Inspired by the flavour of perfectly ripened bananas, this premium disposable vape delivers a sweet, fruity, and satisfying vaping experience that's…",
  },
  {
    slug: "jnr-cruiser-magic-mango-12000-puffs",
    name: "JNR Cruiser Magic Mango 12000 - Puffs",
    category: "disposables",
    categoryLabel: "JNR Cruiser 12000 Puffs",
    price: 84.95,
    salePrice: 69.95,
    image: "/products/jnr-cruiser-magic-mango-12000-puffs.jpg",
    flavour: "Magic Mango 12000 - Puffs",
    puffs: "12000",
    nicotine: "20 mg/mL",
    description: "Indulge in the tropical sweetness of the JNR Cruiser Magic Mango 12000 Puffs. Bursting with the rich and juicy flavour of perfectly ripened mangoes, this premium disposable vape delivers a smooth, fruity experience that's ideal for mango…",
  },
  {
    slug: "iget-one-strawberry-pomegranate-12000-puffs",
    name: "IGET One Strawberry Pomegranate",
    category: "disposables",
    categoryLabel: "IGET One 12000 Puffs",
    price: 89.95,
    salePrice: 84.95,
    image: "/products/iget-one-strawberry-pomegranate-12000-puffs.jpg",
    flavour: "Strawberry Pomegranate",
    puffs: "12000",
    nicotine: "20 mg/mL",
    description: "🍓 Overview The IGET ONE Strawberry Pomegranate delivers a bold, fruit-forward vape with up to 12,000 puffs, combining sweet strawberry and rich pomegranate for a smooth all-day experience.",
  },
  {
    slug: "panda-watermelon-ice-2500-puffs",
    name: "Panda Watermelon Ice",
    category: "disposables",
    categoryLabel: "Panda 2500 Puffs",
    price: 34.95,
    salePrice: 19.95,
    image: "/products/panda-watermelon-ice-2500-puffs.webp",
    flavour: "Watermelon Ice",
    puffs: "2500",
    nicotine: "20 mg/mL",
    description: "🍉 Overview Crisp disposable vape with juicy watermelon and cool menthol vibes, delivering up to 2500 puffs.",
  },
  {
    slug: "iget-bar-pro-dynamic-mint-10000-puffs",
    name: "IGET Bar Pro Dynamic Mint",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 79.95,
    salePrice: 69.95,
    image: "/products/iget-bar-pro-dynamic-mint-10000-puffs.jpg",
    flavour: "Dynamic Mint",
    puffs: "10000",
    battery: "2000mAh",
    nicotine: "20 mg/mL",
    description: "🍃 Overview The IGET BAR PRO Dynamic Mint – 10,000 Puffs offers a crisp and refreshing mint experience with an invigorating icy finish. Designed for those who love clean, menthol-style vapes, it delivers a cool, satisfying sensation with…",
  },
  {
    slug: "iget-bar-pro-chupa-chups-strawberry-10000-puffs",
    name: "IGET Bar Pro Chupa Chups Strawberry",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 79.95,
    salePrice: 69.95,
    image: "/products/iget-bar-pro-chupa-chups-strawberry-10000-puffs.jpg",
    flavour: "Chupa Chups Strawberry",
    puffs: "10000",
    nicotine: "20 mg/mL",
    description: "🍓 Overview The IGET BAR PRO Chupa Chups Strawberry – 10,000 Puffs delivers the iconic candy-lollipop sweetness of strawberry wrapped in a sleek, long-lasting disposable design. It’s ideal for users who enjoy bold, sweet flavors with no…",
  },
  {
    slug: "iget-bar-pro-strawberry-white-peach-ice-mist-10000-puffs",
    name: "IGET Bar Pro Strawberry White Peach Ice Mist",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 79.95,
    salePrice: 69.95,
    image: "/products/iget-bar-pro-strawberry-white-peach-ice-mist-10000-puffs.jpg",
    flavour: "Strawberry White Peach Ice Mist",
    puffs: "10000",
    battery: "2000mAh",
    capacity: "20mL",
    nicotine: "50 mg/mL",
    description: "🍓 Overview The IGET BAR PRO Strawberry White Peach Ice Mist – 10,000 Puffstreet delivers a sophisticated blend of juicy strawberries and soft white peaches, topped with a crisp icy finish. Each draw offers a smooth, fruity experience with…",
  },
  {
    slug: "iget-bar-pro-raspberry-pomegrante-ice-blast-10000-puffs",
    name: "IGET Bar Pro Raspberry Pomegrante Ice Blast",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 79.95,
    salePrice: 69.95,
    image: "/products/iget-bar-pro-raspberry-pomegrante-ice-blast-10000-puffs.jpg",
    flavour: "Raspberry Pomegrante Ice Blast",
    puffs: "10000",
    battery: "2000mAh",
    nicotine: "20 mg/mL",
    description: "🍇 Overview The IGET BAR PRO Raspberry Pomegranate Ice Blast – 10,000 Puffs delivers a vibrant fruit blend where juicy raspberries and bold pomegranate meet a crisp menthol exhale. Each puff offers a layered, refreshing taste with a smooth…",
  },
  {
    slug: "fisco-xpod-8000-puffs-device-only",
    name: "Fisco Xpod 8000 Puffs (device Only)",
    category: "disposables",
    categoryLabel: "Fisco Xpod",
    price: 59.95,
    image: "/products/fisco-xpod-8000-puffs-device-only.jpg",
    flavour: "8000 Puffs (device Only)",
    puffs: "8000",
    nicotine: "20 mg/mL",
    description: "🍃 Overview The FISCO XPOD 8000 Puffs (Device Only) is a sleek, compact vaping device designed for use with compatible pods. It offers up to 8,000 draws, making it a practical choice for convenience‑seeking vapers who want a reliable,…",
  },
  {
    slug: "fisco-xpod-cherry-pomegrante-8000-puffs-pod-only",
    name: "Fisco Xpod Cherry Pomegrante - 8000 Puffs (pod Only)",
    category: "disposables",
    categoryLabel: "Fisco Xpod",
    price: 59.95,
    image: "/products/fisco-xpod-cherry-pomegrante-8000-puffs-pod-only.jpg",
    flavour: "Cherry Pomegrante - 8000 Puffs (pod Only)",
    puffs: "8000",
    nicotine: "20 mg/mL",
    description: "🍒 Overview The FISCO Xpod Cherry Pomegranate 8000 Puffs (Pod Only) offers a rich fruit blend where the sweet, familiar taste of cherries mixes with the tangy, bold character of pomegranate—designed for convenient, compact use and…",
  },
  {
    slug: "fisco-xpod-blackberry-pomegrante-cherry-ice-8000-puffs-pod-only",
    name: "Fisco Xpod Blackberry Pomegrante Cherry Ice - 8000 Puffs (pod Only)",
    category: "disposables",
    categoryLabel: "Fisco Xpod",
    price: 59.95,
    image: "/products/fisco-xpod-blackberry-pomegrante-cherry-ice-8000-puffs-pod-only.jpg",
    flavour: "Blackberry Pomegrante Cherry Ice - 8000 Puffs (pod Only)",
    puffs: "8000",
    nicotine: "20 mg/mL",
    description: "🍒 Overview The FISCO Xpod Blackberry Pomegranate Cherry Ice (Pod Only) – 8,000 Puffs delivers a layered fruit-blend experience where juicy blackberries meet bright pomegranate and sweet cherries, all topped with a cool menthol finish.…",
  },
  {
    slug: "iget-bar-pro-chupa-chups-grape-10000-puffs",
    name: "IGET Bar Pro Chupa Chups Grape",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 79.95,
    salePrice: 69.95,
    image: "/products/iget-bar-pro-chupa-chups-grape-10000-puffs.jpg",
    flavour: "Chupa Chups Grape",
    puffs: "10000",
    battery: "2000mAh",
    capacity: "22mL",
    nicotine: "50 mg/mL",
    description: "🍇 Overview The IGET BAR PRO Chupa Chups Grape 10,000 Puffs delivers a bold and playful grape candy experience—think of the classic Chupa Chups lollipop flavour captured in a vaping device. It’s sweet, juicy, and designed to deliver…",
  },
  {
    slug: "iget-bar-pro-fruity-skittles-10000-puffs",
    name: "IGET Bar Pro Fruity Skittles",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 79.95,
    salePrice: 69.95,
    image: "/products/iget-bar-pro-fruity-skittles-10000-puffs.jpg",
    flavour: "Fruity Skittles",
    puffs: "10000",
    nicotine: "20 mg/mL",
    description: "🍬 Overview The IGET Bar Pro Fruity Skittles 10000 Puffstreet delivers a vibrant, playful flavor experience reminiscent of a rainbow-packed fruit candy. Each puff brings a mix of bold, sweet fruit notes that feel like a party in your…",
  },
  {
    slug: "iget-bar-pro-mango-ice-10000-puffs",
    name: "IGET Bar Pro Mango Ice",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 79.95,
    salePrice: 69.95,
    image: "/products/iget-bar-pro-mango-ice-10000-puffs.jpg",
    flavour: "Mango Ice",
    puffs: "10000",
    battery: "2000mAh",
    nicotine: "20 mg/mL",
    description: "🥭 Overview The IGET BAR PRO Mango Ice 10000 Puffstreet delivers a smooth tropical rush of juicy mango blended perfectly with an icy menthol twist. It’s sweet, refreshing, and ideal for users who enjoy a fruity chill in every puff.",
  },
  {
    slug: "iget-bar-pro-blueberry-raspberry-bubble-gum-10000-puffs",
    name: "IGET Bar Pro Blueberry Raspberry Bubble Gum",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 79.95,
    salePrice: 69.95,
    image: "/products/iget-bar-pro-blueberry-raspberry-bubble-gum-10000-puffs.jpg",
    flavour: "Blueberry Raspberry Bubble Gum",
    puffs: "10000",
    battery: "2000mAh",
    capacity: "20mL",
    nicotine: "50 mg/mL",
    description: "🍬 Overview The IGET Bar Pro Blueberry Raspberry Bubble Gum – 10,000 Puffstreet offers a vibrant, candy-inspired flavor experience. It features juicy blueberries and tart raspberries layered over a sweet bubble gum base—designed for those…",
  },
  {
    slug: "iget-bar-pro-passion-fruit-peach-ice-tea-10000-puffs",
    name: "IGET Bar Pro Passion Fruit Peach Ice Tea",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 79.95,
    salePrice: 69.95,
    image: "/products/iget-bar-pro-passion-fruit-peach-ice-tea-10000-puffs.jpg",
    flavour: "Passion Fruit Peach Ice Tea",
    puffs: "10000",
    battery: "2,000mAh",
    capacity: "20mL",
    nicotine: "50 mg/mL",
    description: "🍹 Overview The IGET BAR PRO Passion Fruit Peach Ice Tea (10,000 puffs) offers a refreshing blend of tropical passionfruit, ripe peach, and a crisp iced tea finish. This flavor is designed to deliver a cool, fruity beverage-inspired vaping…",
  },
  {
    slug: "iget-bar-pro-cherry-pomegranate-10000-puffs-2",
    name: "IGET Bar Pro Cherry Pomegranate",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 79.95,
    salePrice: 69.95,
    image: "/products/iget-bar-pro-cherry-pomegranate-10000-puffs-2.jpg",
    flavour: "Cherry Pomegranate",
    puffs: "10000",
    battery: "2000mAh",
    nicotine: "20 mg/mL",
    description: "🍒 Overview The IGET BAR PRO Cherry Pomegranate 10000 Puffs delivers a bold, fruity blend where sweet cherry meets the tangy depth of pomegranate. Each puff bursts with rich, juicy flavor for an indulgent yet refreshing vape experience.",
  },
  {
    slug: "alibarbar-ingot-yellow-starburst-9000-puffs",
    name: "Alibarbar Ingot Yellow Starburst",
    category: "disposables",
    categoryLabel: "Alibarbar 9000",
    price: 79.95,
    image: "/products/alibarbar-ingot-yellow-starburst-9000-puffs.jpg",
    flavour: "Ingot Yellow Starburst",
    puffs: "9000",
    nicotine: "20 mg/mL",
    description: "Product Specifications: E-liquid Capacity: 22ml Battery Capacity: 2350mah Puffs: Up to 9000 Size: 103x40x26mm Net Weight: 90g Coil Resistance: 1.2Ω Non-rechargeable LED display",
  },
  {
    slug: "iget-bar-pro-strawberry-passionfruit-mango-10000-puffs",
    name: "IGET Bar Pro Strawberry Passionfruit Mango",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 79.95,
    salePrice: 69.95,
    image: "/products/iget-bar-pro-strawberry-passionfruit-mango-10000-puffs.jpg",
    flavour: "Strawberry Passionfruit Mango",
    puffs: "10000",
    capacity: "20mL",
    nicotine: "20 mg/mL",
    description: "🍓 Overview The IGET Bar Pro Strawberry Passionfruit Mango 10000 Puffstreet delivers a tropical fruit medley combining the sweet juiciness of strawberries, the tangy zest of passionfruit, and the smooth richness of mango. Each puff offers…",
  },
  {
    slug: "iget-bar-pro-raspberry-cherry-blackberry-10000-puffs",
    name: "IGET Bar Pro Raspberry Cherry Blackberry",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 79.95,
    salePrice: 69.95,
    image: "/products/iget-bar-pro-raspberry-cherry-blackberry-10000-puffs.jpg",
    flavour: "Raspberry Cherry Blackberry",
    puffs: "10000",
    nicotine: "20 mg/mL",
    description: "🍇 Overview The IGET Bar Pro Raspberry Cherry Blackberry 10000 Puffstreet delivers a vibrant berry medley that blends the sweet tartness of raspberries , the juicy burst of cherries, and the rich depth of blackberries. Each puff offers a…",
  },
  {
    slug: "iget-bar-pro-blackberry-yogurt-ice-berry-10000-puffs",
    name: "IGET Bar Pro Blackberry Yogurt Ice Berry",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 79.95,
    salePrice: 69.95,
    image: "/products/iget-bar-pro-blackberry-yogurt-ice-berry-10000-puffs.jpg",
    flavour: "Blackberry Yogurt Ice Berry",
    puffs: "10000",
    nicotine: "20 mg/mL",
    description: "🍇 Overview The IGET Bar Pro Blackberry Yogurt Ice Berry 10000 Puffstreet delivers a luscious fusion of tart blackberries , creamy yogurt, and a refreshing icy finish. Each puff offers a smooth, dessert-inspired experience with a balanced…",
  },
  {
    slug: "iget-bar-pro-strawberry-cranberry-bliss-10000-puffs",
    name: "IGET Bar Pro Strawberry Cranberry Bliss",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 79.95,
    salePrice: 69.95,
    image: "/products/iget-bar-pro-strawberry-cranberry-bliss-10000-puffs.jpg",
    flavour: "Strawberry Cranberry Bliss",
    puffs: "10000",
    nicotine: "20 mg/mL",
    description: "🍓 Overview The IGET Bar Pro Strawberry Cranberry Bliss 10000 Puffstreet delivers a vibrant fruit blend that pairs the sweet juiciness of strawberries with the tart nuance of cranberry. Balanced, refreshing, and lively — it’s a go-to for…",
  },
  {
    slug: "iget-one-grape-ice-12000-puffs",
    name: "IGET One - Grape Ice",
    category: "disposables",
    categoryLabel: "IGET One 12000 Puffs",
    price: 89.95,
    salePrice: 84.95,
    image: "/products/iget-one-grape-ice-12000-puffs.jpg",
    flavour: "- Grape Ice",
    puffs: "12000",
    nicotine: "20 mg/mL",
    description: "🍇 Overview The IGET ONE Grape Ice 12000 Puffs delivers a burst of sweet, juicy grape flavor perfectly balanced with a cool icy finish. Each puff combines fruity smoothness with a refreshing chill, making it a standout choice for fans of…",
  },
  {
    slug: "vapehub-classic-tobacco-20000-puffs-2",
    name: "Vapehub Classic Tobacco",
    category: "disposables",
    categoryLabel: "Vapehub",
    price: 59.95,
    image: "/products/vapehub-classic-tobacco-20000-puffs-2.jpg",
    flavour: "Classic Tobacco",
    puffs: "20000",
    battery: "800mAh",
    capacity: "22mL",
    nicotine: "50 mg/mL",
    description: "🍂 Overview The VAPEHUB Classic Tobacco is an ultra high-capacity disposable vape delivering up to 20,000 puffs , designed for MTL users seeking a deep, rich tobacco flavor in a long-lasting, rechargeable device.",
  },
  {
    slug: "iget-one-kiwi-pineapple-10000-puffs",
    name: "IGET One Kiwi Pineapple",
    category: "disposables",
    categoryLabel: "IGET One 12000 Puffs",
    price: 89.95,
    salePrice: 84.95,
    image: "/products/iget-one-kiwi-pineapple-10000-puffs.jpg",
    flavour: "Kiwi Pineapple",
    puffs: "12000",
    nicotine: "50 mg/mL",
    description: "🍭 Overview A tropical twist from IGET ONE, delivering up to 10,000 puffs of vibrant kiwi and pineapple flavor in a sleek, high-capacity disposable.",
  },
  {
    slug: "iget-one-chupa-chups-strawberry-10000-puffs-2",
    name: "IGET One Chupa Chups Strawberry",
    category: "disposables",
    categoryLabel: "IGET One 12000 Puffs",
    price: 89.95,
    salePrice: 84.95,
    image: "/products/iget-one-chupa-chups-strawberry-10000-puffs-2.jpg",
    flavour: "Chupa Chups Strawberry",
    puffs: "12000",
    nicotine: "50 mg/mL",
    description: "🍭 Overview A refreshing mix from IGET ONE delivering up to 10,000 puffs of sweet strawberry, tangy pomegranate, and a cool icy finish.",
  },
  {
    slug: "iget-one-strawberry-raspberry-10000-puffs",
    name: "IGET One Strawberry Raspberry",
    category: "disposables",
    categoryLabel: "IGET One 12000 Puffs",
    price: 89.95,
    salePrice: 84.95,
    image: "/products/iget-one-strawberry-raspberry-10000-puffs.jpg",
    flavour: "Strawberry Raspberry",
    puffs: "12000",
    nicotine: "50 mg/mL",
    description: "🍭 Overview A fruity fusion from IGET ONE offering up to 10,000 puffs of vibrant strawberry and tangy raspberry in a premium disposable vape.",
  },
  {
    slug: "iget-one-black-forest-10000-puffs",
    name: "IGET One Black Forest",
    category: "disposables",
    categoryLabel: "IGET One 12000 Puffs",
    price: 89.95,
    salePrice: 84.95,
    image: "/products/iget-one-black-forest-10000-puffs.jpg",
    flavour: "Black Forest",
    puffs: "12000",
    nicotine: "50 mg/mL",
    description: "🍭 Overview A dessert-inspired vape from IGET ONE offering up to 10,000 puffs of rich Black Forest flavor in a sleek, long-lasting disposable.",
  },
  {
    slug: "iget-one-chupa-chups-grape-10000-puffs",
    name: "IGET One Chupa Chups Grape",
    category: "disposables",
    categoryLabel: "IGET One 12000 Puffs",
    price: 89.95,
    salePrice: 84.95,
    image: "/products/iget-one-chupa-chups-grape-10000-puffs.jpg",
    flavour: "Chupa Chups Grape",
    puffs: "12000",
    nicotine: "50 mg/mL",
    description: "🍭 Overview A candy-inspired disposable from IGET ONE delivering up to 10,000 puffs of authentic Chupa Chups grape sweetness.",
  },
  {
    slug: "iget-one-tropical-orange-monster-10000-puffs",
    name: "IGET One Tropical Orange Monster",
    category: "disposables",
    categoryLabel: "IGET One 12000 Puffs",
    price: 89.95,
    salePrice: 84.95,
    image: "/products/iget-one-tropical-orange-monster-10000-puffs.jpg",
    flavour: "Tropical Orange Monster",
    puffs: "12000",
    nicotine: "50 mg/mL",
    description: "🍭 Overview A vibrant tropical blend from IGET ONE delivering up to 10,000 puffs of zesty orange and exotic fruity notes in a premium disposable vape.",
  },
  {
    slug: "iget-one-mixed-berries-ice-10000-puffs",
    name: "IGET One Mixed Berries Ice",
    category: "disposables",
    categoryLabel: "IGET One 12000 Puffs",
    price: 89.95,
    salePrice: 84.95,
    image: "/products/iget-one-mixed-berries-ice-10000-puffs.jpg",
    flavour: "Mixed Berries Ice",
    puffs: "12000",
    nicotine: "50 mg/mL",
    description: "🍭 Overview A refreshing berry medley from IGET ONE delivering up to 10,000 puffs of sweet, tangy mixed berries with a cool icy finish.",
  },
  {
    slug: "iget-one-blue-monster-10000-puffs",
    name: "IGET One Blue Monster",
    category: "disposables",
    categoryLabel: "IGET One 12000 Puffs",
    price: 89.95,
    salePrice: 84.95,
    image: "/products/iget-one-blue-monster-10000-puffs.jpg",
    flavour: "Blue Monster",
    puffs: "12000",
    nicotine: "50 mg/mL",
    description: "🍭 Overview A bold energy-drink-inspired vape from IGET ONE, delivering up to 10,000 puffs of sweet, tangy, and invigorating flavor in a high-capacity disposable.",
  },
  {
    slug: "iget-one-cherry-monster-10000-puffs",
    name: "IGET One Cherry Monster",
    category: "disposables",
    categoryLabel: "IGET One 12000 Puffs",
    price: 89.95,
    salePrice: 84.95,
    image: "/products/iget-one-cherry-monster-10000-puffs.jpg",
    flavour: "Cherry Monster",
    puffs: "12000",
    nicotine: "50 mg/mL",
    description: "🍭 Overview An energizing cherry-flavored vape from IGET ONE, delivering up to 10,000 puffs of sweet-tart cherry with an energy drink twist.",
  },
  {
    slug: "iget-one-mountain-spring-mint-ice-10000-puffs",
    name: "IGET One Mountain Spring Mint Ice",
    category: "disposables",
    categoryLabel: "IGET One 12000 Puffs",
    price: 89.95,
    salePrice: 84.95,
    image: "/products/iget-one-mountain-spring-mint-ice-10000-puffs.jpg",
    flavour: "Mountain Spring Mint Ice",
    puffs: "12000",
    nicotine: "50 mg/mL",
    description: "🍭 Overview A crisp and refreshing vape from IGET ONE, offering up to 10,000 puffs of cool mountain spring water infused with icy mint freshness.",
  },
  {
    slug: "iget-one-blueberry-raspberry-10000-puffs",
    name: "IGET One Blueberry Raspberry",
    category: "disposables",
    categoryLabel: "IGET One 12000 Puffs",
    price: 89.95,
    salePrice: 84.95,
    image: "/products/iget-one-blueberry-raspberry-10000-puffs.jpg",
    flavour: "Blueberry Raspberry",
    puffs: "12000",
    nicotine: "50 mg/mL",
    description: "🍭 Overview A berry-packed vape from IGET ONE offering up to 10,000 puffs of sweet blueberry and tangy raspberry fusion in a premium disposable.",
  },
  {
    slug: "iget-one-blueberry-ice-10000-puffs",
    name: "IGET One Blueberry Ice",
    category: "disposables",
    categoryLabel: "IGET One 12000 Puffs",
    price: 89.95,
    salePrice: 84.95,
    image: "/products/iget-one-blueberry-ice-10000-puffs.jpg",
    flavour: "Blueberry Ice",
    puffs: "12000",
    nicotine: "50 mg/mL",
    description: "🍭 Overview A refreshing berry-menthol blend from IGET ONE, delivering up to 10,000 puffs of sweet blueberry with an icy kick in a sleek disposable.",
  },
  {
    slug: "iget-one-cherry-pomegranate-10000-puffs",
    name: "IGET One Cherry Pomegranate",
    category: "disposables",
    categoryLabel: "IGET One 12000 Puffs",
    price: 89.95,
    salePrice: 84.95,
    image: "/products/iget-one-cherry-pomegranate-10000-puffs.jpg",
    flavour: "Cherry Pomegranate",
    puffs: "12000",
    nicotine: "50 mg/mL",
    description: "🍭 Overview A luscious blend from IGET ONE delivering up to 10,000 puffs of sweet cherry combined with tangy pomegranate in a sleek disposable vape.",
  },
  {
    slug: "iget-one-blackberry-cherry-pomegranate-10000-puffs",
    name: "IGET One Blackberry Cherry Pomegranate",
    category: "disposables",
    categoryLabel: "IGET One 12000 Puffs",
    price: 89.95,
    salePrice: 84.95,
    image: "/products/iget-one-blackberry-cherry-pomegranate-10000-puffs.jpg",
    flavour: "Blackberry Cherry Pomegranate",
    puffs: "12000",
    nicotine: "50 mg/mL",
    description: "🍭 Overview A rich and bold blend from IGET ONE delivering up to 10,000 puffs of luscious blackberry, sweet cherry, and tangy pomegranate in a sleek disposable vape.",
  },
  {
    slug: "iget-one-raspberry-grape-ice-10000-puffs",
    name: "IGET One Raspberry Grape Ice",
    category: "disposables",
    categoryLabel: "IGET One 12000 Puffs",
    price: 89.95,
    salePrice: 84.95,
    image: "/products/iget-one-raspberry-grape-ice-10000-puffs.jpg",
    flavour: "Raspberry Grape Ice",
    puffs: "12000",
    nicotine: "50 mg/mL",
    description: "🍭 Overview A cool and fruity vape from IGET ONE offering up to 10,000 puffs of sweet raspberry and juicy grape with an icy menthol finish.",
  },
  {
    slug: "iget-one-strawberry-watermelon-ice-10000-puffs",
    name: "IGET One Strawberry Watermelon Ice",
    category: "disposables",
    categoryLabel: "IGET One 12000 Puffs",
    price: 89.95,
    salePrice: 84.95,
    image: "/products/iget-one-strawberry-watermelon-ice-10000-puffs.jpg",
    flavour: "Strawberry Watermelon Ice",
    puffs: "12000",
    nicotine: "50 mg/mL",
    description: "🍭 Overview A refreshing blend from IGET ONE delivering up to 10,000 puffs of juicy strawberry and sweet watermelon with a cool icy finish.",
  },
  {
    slug: "iget-one-strawberry-kiwi-ice-10000-puffs",
    name: "IGET One Strawberry Kiwi Ice",
    category: "disposables",
    categoryLabel: "IGET One 12000 Puffs",
    price: 89.95,
    salePrice: 84.95,
    image: "/products/iget-one-strawberry-kiwi-ice-10000-puffs.jpg",
    flavour: "Strawberry Kiwi Ice",
    puffs: "12000",
    nicotine: "50 mg/mL",
    description: "🍭 Overview A vibrant fruity blend from IGET ONE delivering up to 10,000 puffs of sweet strawberry and tangy kiwi with an icy menthol twist.",
  },
  {
    slug: "alibarbar-ingot-skittles-9000-puffs",
    name: "Alibarbar Ingot - Skittles",
    category: "disposables",
    categoryLabel: "Alibarbar 9000",
    price: 79.95,
    image: "/products/alibarbar-ingot-skittles-9000-puffs.jpg",
    flavour: "Ingot - Skittles",
    puffs: "9000",
    battery: "2350mAh",
    capacity: "22ml",
    nicotine: "20 mg/mL",
    description: "Product Specifications: E-liquid Capacity: 22ml Battery Capacity: 2350mah Puffs: Up to 9000 Size: 103x40x26mm Net Weight: 90g Coil Resistance: 1.2Ω Non-rechargeable LED display",
  },
  {
    slug: "surprise-pack-worth-2000",
    name: "Surprise Pack Worth $2000",
    category: "disposables",
    categoryLabel: "Promotions",
    price: 2000,
    salePrice: 1395.95,
    image: "/products/surprise-pack-worth-2000.jpg",
    nicotine: "20 mg/mL",
    description: "Introducing the Ultimate Vape Bundle Packs – the best deal for vape enthusiasts looking for premium random vapes and flavours at an unbeatable price!",
  },
  {
    slug: "surprise-pack-worth-1500",
    name: "Surprise Pack Worth $1500",
    category: "disposables",
    categoryLabel: "Promotions",
    price: 1500,
    salePrice: 990,
    image: "/products/surprise-pack-worth-1500.jpg",
    nicotine: "20 mg/mL",
    description: "Introducing the Ultimate Vape Bundle Packs – the best deal for vape enthusiasts looking for premium random vapes and flavours at an unbeatable price!",
  },
  {
    slug: "surprise-box-worth-500",
    name: "Surprise Pack Worth $500",
    category: "disposables",
    categoryLabel: "Promotions",
    price: 500,
    salePrice: 299.95,
    image: "/products/surprise-box-worth-500.jpg",
    nicotine: "20 mg/mL",
    description: "Introducing the Ultimate Vape Bundle Packs – the best deal for vape enthusiasts looking for premium random vapes and flavours at an unbeatable price!",
  },
  {
    slug: "surprise-box-worth-1000",
    name: "Surprise Pack Worth $1000",
    category: "disposables",
    categoryLabel: "Promotions",
    price: 1000,
    salePrice: 649.95,
    image: "/products/surprise-box-worth-1000.jpg",
    nicotine: "20 mg/mL",
    description: "Introducing the Ultimate Vape Bundle Packs – the best deal for vape enthusiasts looking for premium random vapes and flavours at an unbeatable price!",
  },
  {
    slug: "surprise-box-worth-300",
    name: "Surprise Pack Worth $300",
    category: "disposables",
    categoryLabel: "Promotions",
    price: 300,
    salePrice: 179.95,
    image: "/products/surprise-box-worth-300.jpg",
    nicotine: "20 mg/mL",
    description: "Introducing the Ultimate Vape Bundle Packs – the best deal for vape enthusiasts looking for premium random vapes and flavours at an unbeatable price!",
  },
  {
    slug: "surprise-box-worth-200",
    name: "Surprise Pack Worth $200",
    category: "disposables",
    categoryLabel: "Promotions",
    price: 200,
    salePrice: 129.95,
    image: "/products/surprise-box-worth-200.jpg",
    nicotine: "20 mg/mL",
    description: "Introducing the Ultimate Vape Bundle Packs – the best deal for vape enthusiasts looking for premium random vapes and flavours at an unbeatable price!",
  },
  {
    slug: "surprise-box-worth-120",
    name: "Surprise Pack Worth $120",
    category: "disposables",
    categoryLabel: "Promotions",
    price: 120,
    salePrice: 75.95,
    image: "/products/surprise-box-worth-120.jpg",
    nicotine: "20 mg/mL",
    description: "Introducing the Ultimate Vape Bundle Packs – the best deal for vape enthusiasts looking for premium random vapes and flavours at an unbeatable price!",
  },
  {
    slug: "surprise-box-worth-80",
    name: "Surprise Pack Worth $80",
    category: "disposables",
    categoryLabel: "Promotions",
    price: 80,
    salePrice: 49.95,
    image: "/products/surprise-box-worth-80.jpg",
    nicotine: "20 mg/mL",
    description: "Introducing the Ultimate Vape Bundle Packs – the best deal for vape enthusiasts looking for premium random vapes and flavours at an unbeatable price!",
  },
  {
    slug: "alibarbar-ingot-california-sunset-9000-puffs",
    name: "Alibarbar Ingot - California Sunset",
    category: "disposables",
    categoryLabel: "Alibarbar 9000",
    price: 79.95,
    image: "/products/alibarbar-ingot-california-sunset-9000-puffs.jpg",
    flavour: "Ingot - California Sunset",
    puffs: "9000",
    nicotine: "20 mg/mL",
    description: "Product Specifications: E-liquid Capacity: 22ml Battery Capacity: 2350mah Puffs: Up to 9000 Size: 103x40x26mm Net Weight: 90g Coil Resistance: 1.2Ω Non-rechargeable LED display",
  },
  {
    slug: "iget-bar-pro-10000-puffs-20-packs",
    name: "IGET Bar Pro 10000 Puffs - 20 Pack",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 1319,
    image: "/products/iget-bar-pro-10000-puffs-20-packs.jpg",
    flavour: "10000 Puffs - 20 Pack",
    puffs: "10000",
    nicotine: "20 mg/mL",
    description: "Powered by advanced mesh coil technology, each IGET BAR PRO device produces dense, smooth, and flavorful vapor with reliable long-lasting performance. The combination of bold fruit flavours, refreshing icy finishes, and smooth airflow…",
  },
  {
    slug: "iget-bar-pro-10000-puffs-10-packs",
    name: "IGET Bar Pro 10000 Puffs - 10 Pack",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 669.5,
    image: "/products/iget-bar-pro-10000-puffs-10-packs.jpg",
    flavour: "10000 Puffs - 10 Pack",
    puffs: "10000",
    nicotine: "20 mg/mL",
    description: "Powered by advanced mesh coil technology, each IGET BAR PRO device produces dense, smooth, and flavorful vapor with reliable long-lasting performance. The combination of rich fruit flavours, refreshing icy finishes, and smooth airflow…",
  },
  {
    slug: "iget-bar-pro-10000-puffs-5-packs",
    name: "IGET Bar Pro 10000 Puffs - 5 Pack",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 339.75,
    image: "/products/iget-bar-pro-10000-puffs-5-packs.jpg",
    flavour: "10000 Puffs - 5 Pack",
    puffs: "10000",
    nicotine: "20 mg/mL",
    description: "Powered by advanced mesh coil technology, each IGET BAR PRO device produces dense, smooth, and flavorful vapor with reliable long-lasting performance. The combination of rich fruit flavours, refreshing icy finishes, and smooth airflow…",
  },
  {
    slug: "iget-bar-pro-10000-puffs-3-packs",
    name: "IGET Bar Pro 10000 Puffs - 3 Pack",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 206.85,
    image: "/products/iget-bar-pro-10000-puffs-3-packs.jpg",
    flavour: "10000 Puffs - 3 Pack",
    puffs: "10000",
    nicotine: "20 mg/mL",
    description: "Powered by advanced mesh coil technology, each IGET BAR PRO device delivers dense, smooth, and flavorful vapor from the first puff to the last. The long-lasting battery life, rich flavour delivery, and smooth airflow make the 3 Pack a…",
  },
  {
    slug: "iget-bar-pro-blackberry-pomegranate-cherry-10000-puffs",
    name: "IGET Bar Pro - Blackberry Pomegranate Cherry",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 79.95,
    salePrice: 69.95,
    image: "/products/iget-bar-pro-blackberry-pomegranate-cherry-10000-puffs.jpg",
    flavour: "- Blackberry Pomegranate Cherry",
    puffs: "10000",
    nicotine: "20 mg/mL",
    description: "Powered by advanced mesh coil technology, the IGET BAR PRO Blackberry Pomegranate Cherry produces dense, smooth, and flavorful vapor from the first puff to the last. The combination of sweet blackberry, juicy cherry, and tangy pomegranate…",
  },
  {
    slug: "iget-bar-pro-strawberry-raspberry-10000-puffs",
    name: "IGET Bar Pro - Strawberry Raspberry",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 79.95,
    salePrice: 69.95,
    image: "/products/iget-bar-pro-strawberry-raspberry-10000-puffs.jpg",
    flavour: "- Strawberry Raspberry",
    puffs: "10000",
    nicotine: "20 mg/mL",
    description: "Powered by advanced mesh coil technology, the IGET BAR PRO Strawberry Raspberry produces dense, smooth, and flavorful vapor from the first puff to the last. The combination of juicy strawberry sweetness and refreshing raspberry notes…",
  },
  {
    slug: "iget-bar-pro-strawberry-kiwi-ice-10000-puffs",
    name: "IGET Bar Pro - Strawberry Kiwi Ice",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 79.95,
    salePrice: 69.95,
    image: "/products/iget-bar-pro-strawberry-kiwi-ice-10000-puffs.jpg",
    flavour: "- Strawberry Kiwi Ice",
    puffs: "10000",
    nicotine: "20 mg/mL",
    description: "Powered by advanced mesh coil technology, the IGET BAR PRO Strawberry Kiwi Ice produces dense, smooth, and flavorful vapor from the first puff to the last. The combination of juicy strawberry sweetness, tangy kiwi freshness, and icy…",
  },
  {
    slug: "iget-bar-pro-kiwi-pineapple-10000-puffs",
    name: "IGET Bar Pro - Kiwi Pineapple",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 79.95,
    salePrice: 69.95,
    image: "/products/iget-bar-pro-kiwi-pineapple-10000-puffs.jpg",
    flavour: "- Kiwi Pineapple",
    puffs: "10000",
    nicotine: "20 mg/mL",
    description: "Powered by advanced mesh coil technology, the IGET BAR PRO Kiwi Pineapple produces dense, smooth, and flavorful vapor from the first puff to the last. The combination of tangy kiwi freshness and juicy pineapple sweetness creates a vibrant…",
  },
  {
    slug: "iget-bar-pro-blueberry-raspberry-10000-puffs",
    name: "IGET Bar Pro - Blueberry Raspberry",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 79.95,
    salePrice: 69.95,
    image: "/products/iget-bar-pro-blueberry-raspberry-10000-puffs.jpg",
    flavour: "- Blueberry Raspberry",
    puffs: "10000",
    nicotine: "20 mg/mL",
    description: "Powered by advanced mesh coil technology, the IGET BAR PRO Blueberry Raspberry produces dense, smooth, and flavorful vapor from the first puff to the last. The combination of juicy blueberry sweetness and tangy raspberry notes creates a…",
  },
  {
    slug: "iget-bar-pro-blackberry-ice-10000-puffs",
    name: "IGET Bar Pro - Blackberry Ice",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 79.95,
    salePrice: 69.95,
    image: "/products/iget-bar-pro-blackberry-ice-10000-puffs.jpg",
    flavour: "- Blackberry Ice",
    puffs: "10000",
    nicotine: "20 mg/mL",
    description: "Powered by advanced mesh coil technology, the IGET BAR PRO Blackberry Ice produces dense, smooth, and flavorful vapor from the first puff to the last. The combination of deep blackberry sweetness and refreshing icy notes creates a cool and…",
  },
  {
    slug: "iget-bar-pro-raspberry-grape-10000-puffs",
    name: "IGET Bar Pro - Raspberry Grape",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 79.95,
    salePrice: 69.95,
    image: "/products/iget-bar-pro-raspberry-grape-10000-puffs.jpg",
    flavour: "- Raspberry Grape",
    puffs: "10000",
    nicotine: "20 mg/mL",
    description: "The tangy raspberry notes blend perfectly with the deep and juicy grape flavour, creating a smooth and vibrant inhale with a naturally sweet finish. Whether you enjoy mixed berry disposable vapes or bold fruit combinations, Raspberry Grape…",
  },
  {
    slug: "iget-bar-pro-cherry-pomegranate-10000-puffs",
    name: "IGET Bar Pro - Cherry Pomegranate",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 79.95,
    salePrice: 69.95,
    image: "/products/iget-bar-pro-cherry-pomegranate-10000-puffs.jpg",
    flavour: "- Cherry Pomegranate",
    puffs: "10000",
    nicotine: "20 mg/mL",
    description: "Powered by advanced mesh coil technology, the IGET BAR PRO Cherry Pomegranate produces dense, smooth, and flavorful vapor from the first puff to the last. The combination of juicy cherry sweetness and refreshing pomegranate notes creates a…",
  },
  {
    slug: "iget-bar-pro-strawberry-watermelon-ice-10000-puffs",
    name: "IGET Bar Pro - Strawberry Watermelon Ice",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 79.95,
    salePrice: 69.95,
    image: "/products/iget-bar-pro-strawberry-watermelon-ice-10000-puffs.jpg",
    flavour: "- Strawberry Watermelon Ice",
    puffs: "10000",
    nicotine: "20 mg/mL",
    description: "The IGET BAR PRO Strawberry Watermelon Ice – 10,000 Puffstreet delivers a refreshing blend of sweet strawberries and juicy watermelon finished with a cool icy exhale. Designed for users who enjoy smooth fruity flavours with a chilled…",
  },
  {
    slug: "iget-bar-pro-blueberry-ice-10000-puffs",
    name: "IGET Bar Pro - Blueberry Ice",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 79.95,
    salePrice: 69.95,
    image: "/products/iget-bar-pro-blueberry-ice-10000-puffs.jpg",
    flavour: "- Blueberry Ice",
    puffs: "10000",
    nicotine: "20 mg/mL",
    description: "The juicy blueberry flavour delivers a sweet berry inhale, while the icy cooling sensation adds a refreshing exhale that keeps the vape crisp and enjoyable throughout the day. Whether you prefer fruity disposable vapes or refreshing…",
  },
  {
    slug: "iget-bar-pro-grape-ice-10000-puffs",
    name: "IGET Bar Pro Grape Ice",
    category: "disposables",
    categoryLabel: "IGET Bar Pro",
    price: 79.95,
    salePrice: 69.95,
    image: "/products/iget-bar-pro-grape-ice-10000-puffs.jpg",
    flavour: "Grape Ice",
    puffs: "10000",
    nicotine: "20 mg/mL",
    description: "The sweet grape flavour creates a rich and juicy inhale, while the icy cooling sensation adds a crisp and refreshing finish that keeps every puff smooth and satisfying. Whether you enjoy fruity disposable vapes or refreshing ice flavours,…",
  },
  {
    slug: "hqd-slick-raspberry-grape-6000-puffs",
    name: "HQD Slick Raspberry Grape",
    category: "disposables",
    categoryLabel: "HQD Slick 6000",
    price: 44.95,
    image: "/products/hqd-slick-raspberry-grape-6000-puffs.jpg",
    flavour: "Raspberry Grape",
    puffs: "6000",
    battery: "1400mAH",
    capacity: "15ml",
    nicotine: "20 mg/mL",
    description: "The 12mm-slim CUVIE SLICK brings an ultralight function that moves the way you do, so you can put it in your pockets or hold it in your hand with ease on the go. With an only weight of 70g, CUVIE SLICK is designed to make your travel…",
  },
  {
    slug: "hqd-slick-mango-honeydew-ice-6000-puffs",
    name: "HQD Slick Mango Honeydew Ice",
    category: "disposables",
    categoryLabel: "HQD Slick 6000",
    price: 44.95,
    image: "/products/hqd-slick-mango-honeydew-ice-6000-puffs.jpg",
    flavour: "Mango Honeydew Ice",
    puffs: "6000",
    battery: "1400mAH",
    capacity: "15ml",
    nicotine: "20 mg/mL",
    description: "The 12mm-slim CUVIE SLICK brings an ultralight function that moves the way you do, so you can put it in your pockets or hold it in your hand with ease on the go. With an only weight of 70g, CUVIE SLICK is designed to make your travel…",
  },
  {
    slug: "alibarbar-ingot-mango-magic-9000-puffs",
    name: "Alibarbar Ingot - Mango Magic",
    category: "disposables",
    categoryLabel: "Alibarbar 9000",
    price: 79.95,
    image: "/products/alibarbar-ingot-mango-magic-9000-puffs.jpg",
    flavour: "Ingot - Mango Magic",
    puffs: "9000",
    nicotine: "20 mg/mL",
    description: "Product Specifications: E-liquid Capacity: 22ml Battery Capacity: 2350mah Puffs: Up to 9000 Size: 103x40x26mm Net Weight: 90g Coil Resistance: 1.2Ω Non-rechargeable LED display",
  },
  {
    slug: "alibarbar-ingot-blueberry-blast-9000-puffs",
    name: "Alibarbar Ingot - Blueberry Blast",
    category: "disposables",
    categoryLabel: "Alibarbar 9000",
    price: 79.95,
    image: "/products/alibarbar-ingot-blueberry-blast-9000-puffs.jpg",
    flavour: "Ingot - Blueberry Blast",
    puffs: "9000",
    nicotine: "20 mg/mL",
    description: "🫐 Flavor Profile The ALIBARBAR INGOT Blueberry Blast 9000 Puffs , available at PuffStreet, delivers a bold and juicy blueberry flavour with a sweet and slightly tangy twist. Each puff brings a rich berry inhale followed by a smooth,…",
  },
  {
    slug: "alibarbar-ingot-watermelon-ice-9000-puffs",
    name: "Alibarbar Ingot - Watermelon Ice",
    category: "disposables",
    categoryLabel: "Alibarbar 9000",
    price: 79.95,
    image: "/products/alibarbar-ingot-watermelon-ice-9000-puffs.jpg",
    flavour: "Ingot - Watermelon Ice",
    puffs: "9000",
    nicotine: "20 mg/mL",
    description: "🍉 Flavor Profile The ALIBARBAR INGOT Watermelon Ice 9000 Puffs , available at PuffStree t, delivers a refreshing blend of juicy watermelon and cool menthol ice. The inhale is sweet, light, and fruity with fresh watermelon notes, while the…",
  },
  {
    slug: "alibarbar-ingot-passionfruit-mango-lime-9000-puffs",
    name: "Alibarbar Ingot - Passionfruit Mango Lime",
    category: "disposables",
    categoryLabel: "Alibarbar 9000",
    price: 79.95,
    image: "/products/alibarbar-ingot-passionfruit-mango-lime-9000-puffs.jpg",
    flavour: "Ingot - Passionfruit Mango Lime",
    puffs: "9000",
    nicotine: "20 mg/mL",
    description: "Product Specifications: E-liquid Capacity: 22ml Battery Capacity: 2350mah Puffs: Up to 9000 Size: 103x40x26mm Net Weight: 90g Coil Resistance: 1.2Ω Non-rechargeable LED display",
  },
  {
    slug: "alibarbar-ingot-kiwi-pineapple-9000-puffs",
    name: "Alibarbar Ingot - Kiwi Pineapple",
    category: "disposables",
    categoryLabel: "Alibarbar 9000",
    price: 79.95,
    image: "/products/alibarbar-ingot-kiwi-pineapple-9000-puffs.jpg",
    flavour: "Ingot - Kiwi Pineapple",
    puffs: "9000",
    nicotine: "20 mg/mL",
    description: "🥝🍍 Flavor Profile The ALIBARBAR INGOT Kiwi Pineapple 9000 Puffs , available at PuffStreet, delivers a refreshing tropical fusion of tangy kiwi and sweet pineapple. The inhale brings a bright, zesty kiwi sharpness, while the pineapple…",
  },
  {
    slug: "hqd-slick-kiwi-lemon-6000-puffs",
    name: "HQD Slick Kiwi Lemon",
    category: "disposables",
    categoryLabel: "HQD Slick 6000",
    price: 44.95,
    image: "/products/hqd-slick-kiwi-lemon-6000-puffs.png",
    flavour: "Kiwi Lemon",
    puffs: "6000",
    battery: "1400mAH",
    capacity: "15ml",
    nicotine: "20 mg/mL",
    description: "The 12mm-slim CUVIE SLICK brings an ultralight function that moves the way you do, so you can put it in your pockets or hold it in your hand with ease on the go. With an only weight of 70g, CUVIE SLICK is designed to make your travel…",
  },
];

export const getProduct = (slug: string) => products.find(p => p.slug === slug);
export const bestsellers = () => products.filter(p => p.bestseller);
export const byCategory = (c: string) => products.filter(p => p.category === c);

export const categories = [
  { slug: "disposables", label: "Disposables", blurb: "Pocket-ready pods, no refills." },
  { slug: "devices", label: "Devices", blurb: "Refillable mods and pens." },
  { slug: "best-sellers", label: "Best Sellers", blurb: "This month's top rated." },
];
