import product1 from "@/assets/product-1.jpg";
import product2 from "@/assets/product-2.jpg";
import product3 from "@/assets/product-3.jpg";
import product4 from "@/assets/product-4.jpg";
import rivalLime from "@/assets/rival-bar-lime.jpg.asset.json";
import rivalCola from "@/assets/rival-bar-cola.png.asset.json";
import rivalLongJin from "@/assets/rival-bar-long-jin-tea.png.asset.json";
import rivalGrape from "@/assets/rival-bar-grape.jpg.asset.json";
import alibarbarSCW from "@/assets/alibarbar-strawberry-coconut-watermelon.jpg.asset.json";
import vapehubTobacco from "@/assets/vapehub-classic-tobacco.jpg.asset.json";
import fiscoXpro from "@/assets/fisco-xpro-device.jpg.asset.json";
import fiscoApple from "@/assets/fisco-xpod-apple-shisha.png.asset.json";

const IMG = {
  rivalLime: rivalLime.url,
  rivalCola: rivalCola.url,
  rivalLongJin: rivalLongJin.url,
  rivalGrape: rivalGrape.url,
  alibarbarSCW: alibarbarSCW.url,
  vapehubTobacco: vapehubTobacco.url,
  fiscoXpro: fiscoXpro.url,
  fiscoApple: fiscoApple.url,
};

export type Product = {
  slug: string;
  name: string;
  category: "disposables" | "devices" | "accessories";
  categoryLabel: string;
  price: number;
  salePrice?: number;
  image: string;
  images?: string[];
  flavour?: string;
  puffs?: string;
  battery?: string;
  capacity?: string;
  nicotine?: string;
  colors?: { name: string; hex: string }[];
  description: string;
  bestseller?: boolean;
};

export const products: Product[] = [
  {
    slug: "obsidian-pod-x1",
    name: "Obsidian Pod X1",
    category: "disposables",
    categoryLabel: "Disposable",
    price: 34.95,
    salePrice: 29.95,
    image: product1,
    flavour: "Iced Mango",
    puffs: "6000",
    battery: "650 mAh",
    capacity: "12 mL",
    nicotine: "20 mg/mL",
    colors: [
      { name: "Void", hex: "#0A0A0C" },
      { name: "Bronze", hex: "#A9791F" },
    ],
    description: "A refined pocket device with mesh coil delivery and a stabilised airflow chamber. Designed for a clean, consistent draw.",
    bestseller: true,
  },
  {
    slug: "monolith-mod-450",
    name: "Monolith Mod 450",
    category: "devices",
    categoryLabel: "Device",
    price: 129.0,
    image: product2,
    battery: "3000 mAh",
    capacity: "5 mL",
    colors: [
      { name: "Platinum", hex: "#96969B" },
      { name: "Void", hex: "#0A0A0C" },
    ],
    description: "Machined aluminium chassis with adjustable wattage and a dual-coil deck. Built for enthusiasts who value control.",
    bestseller: true,
  },
  {
    slug: "ember-slim-500",
    name: "Ember Slim 500",
    category: "disposables",
    categoryLabel: "Disposable",
    price: 24.95,
    image: product3,
    flavour: "Tobacco Reserve",
    puffs: "3500",
    battery: "500 mAh",
    capacity: "8 mL",
    nicotine: "18 mg/mL",
    colors: [{ name: "Ember", hex: "#A9791F" }, { name: "Void", hex: "#0A0A0C" }],
    description: "Ultra-slim profile finished with an ember-gold detail line. A quiet, tailored experience.",
    bestseller: true,
  },
  {
    slug: "aureus-pen-24",
    name: "Aureus Pen 24",
    category: "devices",
    categoryLabel: "Device",
    price: 89.0,
    salePrice: 74.0,
    image: product4,
    battery: "1500 mAh",
    capacity: "3 mL",
    colors: [{ name: "Gold", hex: "#F0CD6E" }, { name: "Void", hex: "#0A0A0C" }],
    description: "A slim vertical form factor with gold-anodised endcaps. Refillable pod with adjustable airflow.",
    bestseller: true,
  },
  {
    slug: "obsidian-pod-x2",
    name: "Obsidian Pod X2",
    category: "disposables",
    categoryLabel: "Disposable",
    price: 36.95,
    image: product1,
    flavour: "Winter Mint",
    puffs: "6000",
    battery: "650 mAh",
    capacity: "12 mL",
    nicotine: "20 mg/mL",
    description: "Second generation of the X series with a refined mouthpiece and improved coil life.",
  },
  {
    slug: "monolith-coil-pack",
    name: "Monolith Replacement Coils",
    category: "accessories",
    categoryLabel: "Accessory",
    price: 19.95,
    image: product2,
    description: "Five-pack of 0.4Ω mesh coils calibrated for the Monolith Mod 450.",
  },
  {
    slug: "ember-charger",
    name: "Ember Fast Charger",
    category: "accessories",
    categoryLabel: "Accessory",
    price: 24.95,
    image: product3,
    description: "USB-C fast charger with pass-through protection.",
  },
  {
    slug: "aureus-carry-case",
    name: "Aureus Carry Case",
    category: "accessories",
    categoryLabel: "Accessory",
    price: 39.0,
    image: product4,
    description: "Structured leather-effect case with a gold-stitched interior lining.",
  },
  // ——— Extended catalogue ———
  {
    slug: "jnr-cruiser-passion-fruit-mango-lime-12000",
    name: "JNR Cruiser Passion Fruit Mango Lime",
    category: "disposables",
    categoryLabel: "JNR Cruiser 12000",
    price: 39.95,
    image: product1,
    flavour: "Passion Fruit · Mango · Lime",
    puffs: "12000",
    nicotine: "20 mg/mL",
    description: "Long-life JNR Cruiser disposable with a tropical passion fruit, mango and lime blend.",
  },
  {
    slug: "dh-hype-flat-white-12000",
    name: "Double Happiness Hype Flat White",
    category: "disposables",
    categoryLabel: "DH Hype 12000",
    price: 39.95,
    image: product2,
    flavour: "Flat White",
    puffs: "12000",
    nicotine: "20 mg/mL",
    description: "Smooth espresso and steamed milk profile in the DH Hype 12000 series.",
  },
  {
    slug: "dh-hype-greek-yogurt-12000",
    name: "Double Happiness Hype Greek Yogurt",
    category: "disposables",
    categoryLabel: "DH Hype 12000",
    price: 39.95,
    image: product3,
    flavour: "Greek Yogurt",
    puffs: "12000",
    nicotine: "20 mg/mL",
    description: "Creamy tangy Greek yogurt flavour, DH Hype 12000 series.",
  },
  {
    slug: "dh-hype-strawberry-raspberry-12000",
    name: "Double Happiness Hype Strawberry Raspberry",
    category: "disposables",
    categoryLabel: "DH Hype 12000",
    price: 39.95,
    image: product4,
    flavour: "Strawberry · Raspberry",
    puffs: "12000",
    nicotine: "20 mg/mL",
    description: "Ripe strawberry layered with tart raspberry.",
  },
  {
    slug: "dh-hype-strawberry-watermelon-12000",
    name: "Double Happiness Hype Strawberry Watermelon",
    category: "disposables",
    categoryLabel: "DH Hype 12000",
    price: 39.95,
    image: product1,
    flavour: "Strawberry · Watermelon",
    puffs: "12000",
    nicotine: "20 mg/mL",
    description: "Juicy strawberry meets crisp watermelon.",
  },
  {
    slug: "dh-hype-love-66-12000",
    name: "Double Happiness Hype Love 66",
    category: "disposables",
    categoryLabel: "DH Hype 12000",
    price: 39.95,
    image: product2,
    flavour: "Love 66",
    puffs: "12000",
    nicotine: "20 mg/mL",
    description: "Signature mixed-berry blend from the DH Hype line.",
  },
  {
    slug: "dh-hype-cool-mint-12000",
    name: "Double Happiness Hype Cool Mint",
    category: "disposables",
    categoryLabel: "DH Hype 12000",
    price: 39.95,
    image: product3,
    flavour: "Cool Mint",
    puffs: "12000",
    nicotine: "20 mg/mL",
    description: "Clean, icy mint draw.",
  },
  {
    slug: "dh-hype-double-happiness-12000",
    name: "Double Happiness Hype Double Happiness",
    category: "disposables",
    categoryLabel: "DH Hype 12000",
    price: 39.95,
    image: product4,
    flavour: "Double Happiness",
    puffs: "12000",
    nicotine: "20 mg/mL",
    description: "The house signature — sweet fruit medley with a cool finish.",
  },
  {
    slug: "dh-hype-blueberry-raspberry-12000",
    name: "Double Happiness Hype Blueberry Raspberry",
    category: "disposables",
    categoryLabel: "DH Hype 12000",
    price: 39.95,
    image: product1,
    flavour: "Blueberry · Raspberry",
    puffs: "12000",
    nicotine: "20 mg/mL",
    description: "Deep blueberry with a tart raspberry lift.",
  },
  {
    slug: "dh-hype-12000-3-pack",
    name: "Double Happiness Hype 12000 — 3 Pack",
    category: "disposables",
    categoryLabel: "DH Hype 12000",
    price: 109.95,
    salePrice: 99.95,
    image: product2,
    puffs: "12000 x 3",
    nicotine: "20 mg/mL",
    description: "Three-pack bundle of DH Hype 12000 disposables. Mix flavours at checkout.",
  },
  {
    slug: "dh-hype-strawberry-lollipop-12000",
    name: "Double Happiness Hype Strawberry Lollipop",
    category: "disposables",
    categoryLabel: "DH Hype 12000",
    price: 39.95,
    image: product3,
    flavour: "Strawberry Lollipop",
    puffs: "12000",
    nicotine: "20 mg/mL",
    description: "Sweet candied strawberry, lollipop-style.",
  },
  {
    slug: "dh-hype-cherry-pomegranate-12000",
    name: "Double Happiness Hype Cherry Pomegranate",
    category: "disposables",
    categoryLabel: "DH Hype 12000",
    price: 39.95,
    image: product4,
    flavour: "Cherry · Pomegranate",
    puffs: "12000",
    nicotine: "20 mg/mL",
    description: "Dark cherry with pomegranate tang.",
  },
  {
    slug: "dh-hype-blackberry-12000",
    name: "Double Happiness Hype Blackberry",
    category: "disposables",
    categoryLabel: "DH Hype 12000",
    price: 39.95,
    image: product1,
    flavour: "Blackberry",
    puffs: "12000",
    nicotine: "20 mg/mL",
    description: "Bold, jammy blackberry.",
  },
  {
    slug: "alibarbar-ingot-strawberry-lollipop-9000",
    name: "Alibarbar Ingot Strawberry Lollipop",
    category: "disposables",
    categoryLabel: "Alibarbar 9000",
    price: 34.95,
    image: product2,
    flavour: "Strawberry Lollipop",
    puffs: "9000",
    nicotine: "20 mg/mL",
    description: "Candied strawberry in the Alibarbar Ingot 9000 chassis.",
  },
  {
    slug: "alibarbar-ingot-grapefruit-guava-lemon-ice-9000",
    name: "Alibarbar Ingot Grapefruit Guava Lemon Ice",
    category: "disposables",
    categoryLabel: "Alibarbar 9000",
    price: 34.95,
    image: product3,
    flavour: "Grapefruit · Guava · Lemon Ice",
    puffs: "9000",
    nicotine: "20 mg/mL",
    description: "Sharp citrus and guava with a chilled finish.",
  },
  {
    slug: "alibarbar-ingot-ribena-9000",
    name: "Alibarbar Ingot Ribena",
    category: "disposables",
    categoryLabel: "Alibarbar 9000",
    price: 34.95,
    image: product4,
    flavour: "Ribena Blackcurrant",
    puffs: "9000",
    nicotine: "20 mg/mL",
    description: "Nostalgic blackcurrant cordial profile.",
  },
  {
    slug: "alibarbar-ingot-miami-mint-9000",
    name: "Alibarbar Ingot Miami Mint",
    category: "disposables",
    categoryLabel: "Alibarbar 9000",
    price: 34.95,
    image: product1,
    flavour: "Miami Mint",
    puffs: "9000",
    nicotine: "20 mg/mL",
    description: "Bright spearmint with a cooling exhale.",
  },
  {
    slug: "fisco-xpod-double-apple-8000",
    name: "Fisco Xpod Double Apple",
    category: "disposables",
    categoryLabel: "Fisco Xpod",
    price: 32.95,
    image: product2,
    flavour: "Double Apple",
    puffs: "8000",
    nicotine: "20 mg/mL",
    description: "Classic shisha-style double apple in the Fisco Xpod.",
  },
  {
    slug: "fisco-xpod-spearmint-8000-pod-only",
    name: "Fisco Xpod Spearmint (Pod Only)",
    category: "disposables",
    categoryLabel: "Fisco Xpod",
    price: 24.95,
    image: product3,
    flavour: "Spearmint",
    puffs: "8000",
    nicotine: "20 mg/mL",
    description: "Replacement pod only — spearmint flavour, fits the Fisco Xpod device.",
  },
  {
    slug: "calibarn-peach-watermelon-6000",
    name: "Calibarn Peach Watermelon",
    category: "disposables",
    categoryLabel: "Calibarn 6000",
    price: 27.95,
    image: product4,
    flavour: "Peach · Watermelon",
    puffs: "6000",
    nicotine: "20 mg/mL",
    description: "Ripe peach and crisp watermelon.",
  },
  {
    slug: "calibarn-lemon-mint-6000",
    name: "Calibarn Lemon Mint",
    category: "disposables",
    categoryLabel: "Calibarn 6000",
    price: 27.95,
    image: product1,
    flavour: "Lemon · Mint",
    puffs: "6000",
    nicotine: "20 mg/mL",
    description: "Zesty lemon with a cooling mint finish.",
  },
  {
    slug: "rival-bar-lychee-8000",
    name: "Rival Bar Lychee",
    category: "disposables",
    categoryLabel: "Rival Bar 8000",
    price: 32.95,
    image: product2,
    flavour: "Lychee",
    puffs: "8000",
    nicotine: "20 mg/mL",
    description: "Delicate floral lychee.",
  },
  {
    slug: "rival-bar-long-jin-tea-8000",
    name: "Rival Bar Long Jin Tea",
    category: "disposables",
    categoryLabel: "Rival Bar 8000",
    price: 32.95,
    image: product3,
    flavour: "Long Jin Green Tea",
    puffs: "8000",
    nicotine: "20 mg/mL",
    description: "Toasted green tea with a smooth, earthy finish.",
  },
  {
    slug: "rival-bar-lime-8000",
    name: "Rival Bar Lime",
    category: "disposables",
    categoryLabel: "Rival Bar 8000",
    price: 32.95,
    image: product4,
    flavour: "Lime",
    puffs: "8000",
    nicotine: "20 mg/mL",
    description: "Sharp, juicy lime.",
  },
  {
    slug: "rival-bar-cola-8000",
    name: "Rival Bar Cola",
    category: "disposables",
    categoryLabel: "Rival Bar 8000",
    price: 32.95,
    image: product1,
    flavour: "Cola",
    puffs: "8000",
    nicotine: "20 mg/mL",
    description: "Fizzy cola classic.",
  },
];

export const getProduct = (slug: string) => products.find(p => p.slug === slug);
export const bestsellers = () => products.filter(p => p.bestseller);
export const byCategory = (c: string) => products.filter(p => p.category === c);

export const categories = [
  { slug: "disposables", label: "Disposables", blurb: "Pocket-ready pods, no refills." },
  { slug: "devices", label: "Devices", blurb: "Refillable mods and pens." },
  { slug: "accessories", label: "Accessories", blurb: "Coils, chargers, cases." },
  { slug: "best-sellers", label: "Best Sellers", blurb: "This month's top rated." },
];